// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeisFIRaH2nfnh1HYN4QQtny2o1iJTQNw',
    appId: '1:1018287743573:web:95050af62b83c8e3abaadc',
    messagingSenderId: '1018287743573',
    projectId: 'flutterconnection-3fc1f',
    authDomain: 'flutterconnection-3fc1f.firebaseapp.com',
    storageBucket: 'flutterconnection-3fc1f.appspot.com',
    measurementId: 'G-Z32SNHMG0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxJU7mKaABm4nQkXda1BQQKwlRyDEK150',
    appId: '1:1018287743573:android:e8483afde6780107abaadc',
    messagingSenderId: '1018287743573',
    projectId: 'flutterconnection-3fc1f',
    storageBucket: 'flutterconnection-3fc1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFJ_jtN3QQ0ynoVCZnl30qqM9o3xja85c',
    appId: '1:1018287743573:ios:761aa9bdfee6b510abaadc',
    messagingSenderId: '1018287743573',
    projectId: 'flutterconnection-3fc1f',
    storageBucket: 'flutterconnection-3fc1f.appspot.com',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFJ_jtN3QQ0ynoVCZnl30qqM9o3xja85c',
    appId: '1:1018287743573:ios:761aa9bdfee6b510abaadc',
    messagingSenderId: '1018287743573',
    projectId: 'flutterconnection-3fc1f',
    storageBucket: 'flutterconnection-3fc1f.appspot.com',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeisFIRaH2nfnh1HYN4QQtny2o1iJTQNw',
    appId: '1:1018287743573:web:b3efcdc8631b9334abaadc',
    messagingSenderId: '1018287743573',
    projectId: 'flutterconnection-3fc1f',
    authDomain: 'flutterconnection-3fc1f.firebaseapp.com',
    storageBucket: 'flutterconnection-3fc1f.appspot.com',
    measurementId: 'G-8XNYSC57T1',
  );
}
